[phases.setup]
nixPkgs = ['python311', 'nodejs_18', 'postgresql']

[phases.install]
cmds = [
    'pip install --upgrade pip',
    'pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'python manage.py collectstatic --noinput'
]

[start]
cmd = 'python manage.py migrate && gunicorn rpgestor20.wsgi:application --bind 0.0.0.0:$PORT --timeout 120 --workers 2'