# Generated by Django 5.2.4 on 2025-07-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nota',
            field=models.TextField(blank=True, help_text='Nota adicional del pedido', null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('E', 'Enviado'), ('F', 'Finalizado'), ('C', 'Cancelado')], default='B', max_length=1),
        ),
    ]
