# Generated by Django 5.2.4 on 2025-07-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_vendedor_created_at_vendedor_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Presupuesto mensual asignado', max_digits=12),
        ),
    ]
