# Generated by Django 5.2.4 on 2025-07-26 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientefavorito'),
        ('usuarios', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('V', 'Visita a Cliente'), ('L', 'Llamada Telefónica'), ('R', 'Reunión'), ('S', 'Seguimiento'), ('RE', 'Recordatorio'), ('O', 'Otro')], default='V', max_length=2)),
                ('prioridad', models.CharField(choices=[('B', 'Baja'), ('M', 'Media'), ('A', 'Alta'), ('U', 'Urgente')], default='M', max_length=1)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'En Progreso'), ('C', 'Completado'), ('CA', 'Cancelado')], default='P', max_length=2)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=300, null=True)),
                ('recordatorio_enviado', models.BooleanField(default=False)),
                ('minutos_recordatorio', models.IntegerField(default=30, help_text='Minutos antes del evento para enviar recordatorio')),
                ('notas', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_agenda', to='clientes.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_agenda', to='usuarios.vendedor')),
            ],
            options={
                'verbose_name': 'Evento de Agenda',
                'verbose_name_plural': 'Eventos de Agenda',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
