# Generated by Django 5.2.4 on 2025-07-27 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_eventoagenda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoagenda',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó este evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventoagenda',
            name='vendedores_adicionales',
            field=models.ManyToManyField(blank=True, help_text='Vendedores adicionales invitados a la reunión', related_name='eventos_adicionales', to='usuarios.vendedor'),
        ),
    ]
