# Generated by Django 5.2.4 on 2025-07-28 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_eventoagenda_creado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeJefeVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('M', 'Motivacional'), ('A', 'Alerta'), ('F', 'Felicitación'), ('R', 'Recordatorio'), ('RE', 'Reunión')], default='M', max_length=2)),
                ('prioridad', models.CharField(choices=[('B', 'Baja'), ('M', 'Media'), ('A', 'Alta'), ('U', 'Urgente')], default='M', max_length=1)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha_leido', models.DateTimeField(blank=True, null=True)),
                ('jefe', models.ForeignKey(help_text='Jefe de ventas que envía el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to='usuarios.vendedor')),
            ],
            options={
                'verbose_name': 'Mensaje de Jefe de Ventas',
                'verbose_name_plural': 'Mensajes de Jefe de Ventas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetaVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('M', 'Mensual'), ('T', 'Trimestral'), ('A', 'Anual'), ('P', 'Personalizada')], default='M', max_length=1)),
                ('monto_meta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('asignada_por', models.ForeignKey(help_text='Jefe que asignó la meta', on_delete=django.db.models.deletion.CASCADE, related_name='metas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_asignadas', to='usuarios.vendedor')),
            ],
            options={
                'verbose_name': 'Meta de Vendedor',
                'verbose_name_plural': 'Metas de Vendedores',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('R', 'Reunión'), ('E', 'Evaluación'), ('C', 'Coaching'), ('RE', 'Revisión')], default='RE', max_length=2)),
                ('fecha_seguimiento', models.DateTimeField()),
                ('observaciones', models.TextField()),
                ('puntos_fuertes', models.TextField(blank=True, null=True)),
                ('areas_mejora', models.TextField(blank=True, null=True)),
                ('acciones_acordadas', models.TextField(blank=True, null=True)),
                ('calificacion', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Calificación del 1 al 5', null=True)),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_realizados', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='usuarios.vendedor')),
            ],
            options={
                'verbose_name': 'Seguimiento de Vendedor',
                'verbose_name_plural': 'Seguimientos de Vendedores',
                'ordering': ['-fecha_seguimiento'],
            },
        ),
    ]
