# Generated by Django 5.2.4 on 2025-07-28 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_mensajejefeventas_metavendedor_seguimientovendedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('año', models.IntegerField(help_text='Año del presupuesto')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], help_text='Mes del presupuesto')),
                ('monto_presupuesto', models.DecimalField(decimal_places=2, help_text='Monto del presupuesto para este mes específico', max_digits=12)),
                ('observaciones', models.TextField(blank=True, help_text='Notas sobre este presupuesto (ej: temporada alta, promociones, etc.)', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si este presupuesto está activo para el mes correspondiente')),
                ('asignado_por', models.ForeignKey(help_text='Jefe que asignó este presupuesto', on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos_asignados', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos_mensuales', to='usuarios.vendedor')),
            ],
            options={
                'verbose_name': 'Presupuesto Mensual',
                'verbose_name_plural': 'Presupuestos Mensuales',
                'ordering': ['-año', '-mes'],
                'unique_together': {('vendedor', 'año', 'mes')},
            },
        ),
    ]
