# Generated by Django 5.2.4 on 2025-07-22 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.grupo')),
            ],
            options={
                'unique_together': {('nombre', 'grupo')},
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio1', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio3', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio4', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio5', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio6', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.IntegerField()),
                ('externo_id', models.CharField(max_length=50)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.grupo')),
                ('subgrupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.subgrupo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
