# Generated by Django 5.2.4 on 2025-07-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_stockmovimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
