# Generated by Django 5.2.4 on 2025-07-25 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('usuarios', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorito_de', to='clientes.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_favoritos', to='usuarios.vendedor')),
            ],
            options={
                'verbose_name': 'Cliente Favorito',
                'verbose_name_plural': 'Clientes Favoritos',
                'unique_together': {('vendedor', 'cliente')},
            },
        ),
    ]
